<a href="https://colab.research.google.com/github/khaliqtaimoor6-codes/Machine-Learning-Practice/blob/NaiveBayes/NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd

# Corrected URL for the PlayTennis.csv dataset, after further searching
df = pd.read_csv('play_tennis.csv')

print(df)

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [50]:
#outlook =sunny , temp=hot, humidity=high , wind=weak..PLay or no Play?

In [51]:
#P(YES| SUNNY, HOT , HIGH,WEAK)=P(SUNNY|YES )*P(HOT|YES)*P(HIGH|YES)*P(WEAK|YES) *P(YES)
#P(NO|SUNNY , HOT , HIGH , WEAK)=P(SUNNY|NO )*P(HOT|NO)*P(WEAK|NO)*P(WEAK|NO) *P(NO)
#COMPARE AND DECIDE USING THE MAX

In [52]:
#NAIVES BAYES MAKES A LOOKUP TABLE IN FORM OF DICTIONARY

In [53]:
#P(YES)
#P(NO)
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [54]:
py=9/14
pn=5/14
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [55]:
#outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [56]:
Pon=0
Poy=4/9
Prn=2/5
Pry=3/9
Psn=3/5
Psy=2/9
#we take total no nos for each no and totals of yes for each yes

In [57]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [58]:
Pcn=1/5
Phn=2/5
Pmn=2/5
Pcy=3/9
Phighy=2/9
Pmy=4/9

In [59]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [60]:
Phn=4/5
Pnn=1/5
Phy=3/9
Pny=6/9

In [61]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [62]:
Psn=3/5
Pwn=2/5

Psy=3/9
Pwy=6/9

In [64]:
#outlook =sunny , temp=hot, humidity=high , wind=weak..PLay or no Play?

Pyes=py *Psy * Phighy * Phy * Pwy
print(Pyes)
Pno=pn*Psn * Pcn * Phn * Pwn
print(Pno)

0.010582010582010581
0.013714285714285715

In [65]:
np.max([Pyes,Pno])

#No play

np.float64(0.013714285714285715)

In [68]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd

model=CategoricalNB()
X=df.drop(['play', 'day'], axis='columns') # Drop 'day' column as it's not a feature
y=df.play

# Perform one-hot encoding on categorical features
X = pd.get_dummies(X, columns=['outlook', 'temp', 'humidity', 'wind'], drop_first=True)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
accuracy_score(y_test,y_pred)

0.6666666666666666